// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: protos/rl_environment.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 动作: 智能体设置的全局参数
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PCritical  float64 `protobuf:"fixed64,1,opt,name=p_critical,json=pCritical,proto3" json:"p_critical,omitempty"`
	PHigh      float64 `protobuf:"fixed64,2,opt,name=p_high,json=pHigh,proto3" json:"p_high,omitempty"`
	PMedium    float64 `protobuf:"fixed64,3,opt,name=p_medium,json=pMedium,proto3" json:"p_medium,omitempty"`
	PLow       float64 `protobuf:"fixed64,4,opt,name=p_low,json=pLow,proto3" json:"p_low,omitempty"`
	TimeSlotMs float64 `protobuf:"fixed64,5,opt,name=time_slot_ms,json=timeSlotMs,proto3" json:"time_slot_ms,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_rl_environment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rl_environment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_protos_rl_environment_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetPCritical() float64 {
	if x != nil {
		return x.PCritical
	}
	return 0
}

func (x *Action) GetPHigh() float64 {
	if x != nil {
		return x.PHigh
	}
	return 0
}

func (x *Action) GetPMedium() float64 {
	if x != nil {
		return x.PMedium
	}
	return 0
}

func (x *Action) GetPLow() float64 {
	if x != nil {
		return x.PLow
	}
	return 0
}

func (x *Action) GetTimeSlotMs() float64 {
	if x != nil {
		return x.TimeSlotMs
	}
	return 0
}

// 状态: 环境反馈给智能体的观察值
type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Throughput                float64 `protobuf:"fixed64,1,opt,name=throughput,proto3" json:"throughput,omitempty"`
	AvgCollisionRate          float64 `protobuf:"fixed64,2,opt,name=avg_collision_rate,json=avgCollisionRate,proto3" json:"avg_collision_rate,omitempty"`
	AvgWaitTimeMs             float64 `protobuf:"fixed64,3,opt,name=avg_wait_time_ms,json=avgWaitTimeMs,proto3" json:"avg_wait_time_ms,omitempty"`
	PrimaryChannelUtilization float64 `protobuf:"fixed64,4,opt,name=primary_channel_utilization,json=primaryChannelUtilization,proto3" json:"primary_channel_utilization,omitempty"`
	BackupChannelUtilization  float64 `protobuf:"fixed64,5,opt,name=backup_channel_utilization,json=backupChannelUtilization,proto3" json:"backup_channel_utilization,omitempty"`
	TotalRetries              float64 `protobuf:"fixed64,6,opt,name=total_retries,json=totalRetries,proto3" json:"total_retries,omitempty"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_rl_environment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rl_environment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_protos_rl_environment_proto_rawDescGZIP(), []int{1}
}

func (x *State) GetThroughput() float64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

func (x *State) GetAvgCollisionRate() float64 {
	if x != nil {
		return x.AvgCollisionRate
	}
	return 0
}

func (x *State) GetAvgWaitTimeMs() float64 {
	if x != nil {
		return x.AvgWaitTimeMs
	}
	return 0
}

func (x *State) GetPrimaryChannelUtilization() float64 {
	if x != nil {
		return x.PrimaryChannelUtilization
	}
	return 0
}

func (x *State) GetBackupChannelUtilization() float64 {
	if x != nil {
		return x.BackupChannelUtilization
	}
	return 0
}

func (x *State) GetTotalRetries() float64 {
	if x != nil {
		return x.TotalRetries
	}
	return 0
}

// Step 函数的响应
type StepResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NextState *State  `protobuf:"bytes,1,opt,name=next_state,json=nextState,proto3" json:"next_state,omitempty"`
	Reward    float64 `protobuf:"fixed64,2,opt,name=reward,proto3" json:"reward,omitempty"`
	Done      bool    `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"` // 整个仿真会话是否结束
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_rl_environment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rl_environment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_protos_rl_environment_proto_rawDescGZIP(), []int{2}
}

func (x *StepResponse) GetNextState() *State {
	if x != nil {
		return x.NextState
	}
	return nil
}

func (x *StepResponse) GetReward() float64 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *StepResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

// Reset 请求 (可以为空)
type ResetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_rl_environment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_rl_environment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_protos_rl_environment_proto_rawDescGZIP(), []int{3}
}

var File_protos_rl_environment_proto protoreflect.FileDescriptor

var file_protos_rl_environment_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x6c, 0x5f, 0x65, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x65,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x90, 0x01, 0x0a, 0x06, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x5f, 0x63, 0x72, 0x69, 0x74, 0x69,
	0x63, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x70, 0x43, 0x72, 0x69, 0x74,
	0x69, 0x63, 0x61, 0x6c, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x5f, 0x68, 0x69, 0x67, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x48, 0x69, 0x67, 0x68, 0x12, 0x19, 0x0a, 0x08, 0x70,
	0x5f, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x70,
	0x4d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x12, 0x13, 0x0a, 0x05, 0x70, 0x5f, 0x6c, 0x6f, 0x77, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x70, 0x4c, 0x6f, 0x77, 0x12, 0x20, 0x0a, 0x0c, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x6c, 0x6f, 0x74, 0x4d, 0x73, 0x22, 0xa1, 0x02,
	0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x68, 0x72, 0x6f, 0x75,
	0x67, 0x68, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x74, 0x68, 0x72,
	0x6f, 0x75, 0x67, 0x68, 0x70, 0x75, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x61, 0x76, 0x67, 0x5f, 0x63,
	0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x10, 0x61, 0x76, 0x67, 0x43, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a, 0x10, 0x61, 0x76, 0x67, 0x5f, 0x77, 0x61, 0x69,
	0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0d, 0x61, 0x76, 0x67, 0x57, 0x61, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x73, 0x12, 0x3e,
	0x0a, 0x1b, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x5f, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x19, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c,
	0x0a, 0x1a, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x5f, 0x75, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x18, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x22, 0x6d, 0x0a, 0x0c, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x31, 0x0a, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65,
	0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x32, 0x83, 0x01, 0x0a, 0x0d, 0x52, 0x4c, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x38, 0x0a, 0x05, 0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x65, 0x6e,
	0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x04,
	0x53, 0x74, 0x65, 0x70, 0x12, 0x13, 0x2e, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x19, 0x2e, 0x65, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_rl_environment_proto_rawDescOnce sync.Once
	file_protos_rl_environment_proto_rawDescData = file_protos_rl_environment_proto_rawDesc
)

func file_protos_rl_environment_proto_rawDescGZIP() []byte {
	file_protos_rl_environment_proto_rawDescOnce.Do(func() {
		file_protos_rl_environment_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_rl_environment_proto_rawDescData)
	})
	return file_protos_rl_environment_proto_rawDescData
}

var file_protos_rl_environment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_rl_environment_proto_goTypes = []interface{}{
	(*Action)(nil),       // 0: environment.Action
	(*State)(nil),        // 1: environment.State
	(*StepResponse)(nil), // 2: environment.StepResponse
	(*ResetRequest)(nil), // 3: environment.ResetRequest
}
var file_protos_rl_environment_proto_depIdxs = []int32{
	1, // 0: environment.StepResponse.next_state:type_name -> environment.State
	3, // 1: environment.RLEnvironment.Reset:input_type -> environment.ResetRequest
	0, // 2: environment.RLEnvironment.Step:input_type -> environment.Action
	1, // 3: environment.RLEnvironment.Reset:output_type -> environment.State
	2, // 4: environment.RLEnvironment.Step:output_type -> environment.StepResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_rl_environment_proto_init() }
func file_protos_rl_environment_proto_init() {
	if File_protos_rl_environment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_rl_environment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_rl_environment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_rl_environment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StepResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_rl_environment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_rl_environment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_rl_environment_proto_goTypes,
		DependencyIndexes: file_protos_rl_environment_proto_depIdxs,
		MessageInfos:      file_protos_rl_environment_proto_msgTypes,
	}.Build()
	File_protos_rl_environment_proto = out.File
	file_protos_rl_environment_proto_rawDesc = nil
	file_protos_rl_environment_proto_goTypes = nil
	file_protos_rl_environment_proto_depIdxs = nil
}
