// 使用 proto3 语法

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: proto/simulator.proto

// 定义包名，这会映射到 Go 的包名

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义智能体可以执行的动作枚举
type Action int32

const (
	Action_ACTION_WAIT Action = 0 // 代表智能体选择等待
	Action_ACTION_SEND Action = 1 // 代表智能体尝试在主信道发送消息
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_WAIT",
		1: "ACTION_SEND",
	}
	Action_value = map[string]int32{
		"ACTION_WAIT": 0,
		"ACTION_SEND": 1,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_simulator_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_proto_simulator_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_simulator_proto_rawDescGZIP(), []int{0}
}

// [重构后] 定义单个智能体的观测数据结构
// 这将是神经网络的输入，所有维度都使用 float 类型以便于处理
type AgentObservation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsChannelBusy           float32 `protobuf:"fixed32,1,opt,name=is_channel_busy,json=isChannelBusy,proto3" json:"is_channel_busy,omitempty"`                                 // 1. 信道是否忙碌 (1.0 for busy, 0.0 for idle)
	HasDataToSend           float32 `protobuf:"fixed32,2,opt,name=has_data_to_send,json=hasDataToSend,proto3" json:"has_data_to_send,omitempty"`                               // 2. 自身是否有数据待发送 (1.0 for yes, 0.0 for no)
	LastSendCausedCollision float32 `protobuf:"fixed32,3,opt,name=last_send_caused_collision,json=lastSendCausedCollision,proto3" json:"last_send_caused_collision,omitempty"` // 3. 上一次发送是否导致碰撞 (1.0 for collision, 0.0 for no)
	ChannelBusyRatio        float32 `protobuf:"fixed32,4,opt,name=channel_busy_ratio,json=channelBusyRatio,proto3" json:"channel_busy_ratio,omitempty"`                        // 4. 信道拥堵率 (0.0 to 1.0)
	ConsecutiveIdleSteps    float32 `protobuf:"fixed32,5,opt,name=consecutive_idle_steps,json=consecutiveIdleSteps,proto3" json:"consecutive_idle_steps,omitempty"`            // 5. 连续空闲步数
	PacketWaitingTime       float32 `protobuf:"fixed32,6,opt,name=packet_waiting_time,json=packetWaitingTime,proto3" json:"packet_waiting_time,omitempty"`                     // 6. 数据包等待时间 (单位: 步)
	StepsSinceLastCollision float32 `protobuf:"fixed32,7,opt,name=steps_since_last_collision,json=stepsSinceLastCollision,proto3" json:"steps_since_last_collision,omitempty"` // 7. 距离上次碰撞的步数
}

func (x *AgentObservation) Reset() {
	*x = AgentObservation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_simulator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentObservation) ProtoMessage() {}

func (x *AgentObservation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentObservation.ProtoReflect.Descriptor instead.
func (*AgentObservation) Descriptor() ([]byte, []int) {
	return file_proto_simulator_proto_rawDescGZIP(), []int{0}
}

func (x *AgentObservation) GetIsChannelBusy() float32 {
	if x != nil {
		return x.IsChannelBusy
	}
	return 0
}

func (x *AgentObservation) GetHasDataToSend() float32 {
	if x != nil {
		return x.HasDataToSend
	}
	return 0
}

func (x *AgentObservation) GetLastSendCausedCollision() float32 {
	if x != nil {
		return x.LastSendCausedCollision
	}
	return 0
}

func (x *AgentObservation) GetChannelBusyRatio() float32 {
	if x != nil {
		return x.ChannelBusyRatio
	}
	return 0
}

func (x *AgentObservation) GetConsecutiveIdleSteps() float32 {
	if x != nil {
		return x.ConsecutiveIdleSteps
	}
	return 0
}

func (x *AgentObservation) GetPacketWaitingTime() float32 {
	if x != nil {
		return x.PacketWaitingTime
	}
	return 0
}

func (x *AgentObservation) GetStepsSinceLastCollision() float32 {
	if x != nil {
		return x.StepsSinceLastCollision
	}
	return 0
}

// 定义 Step 函数返回的单个智能体的完整结果
type AgentState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Observation *AgentObservation `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	Reward      float32           `protobuf:"fixed32,2,opt,name=reward,proto3" json:"reward,omitempty"`
	Done        bool              `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"` // 标志着一个 episode 是否结束
}

func (x *AgentState) Reset() {
	*x = AgentState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_simulator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentState) ProtoMessage() {}

func (x *AgentState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentState.ProtoReflect.Descriptor instead.
func (*AgentState) Descriptor() ([]byte, []int) {
	return file_proto_simulator_proto_rawDescGZIP(), []int{1}
}

func (x *AgentState) GetObservation() *AgentObservation {
	if x != nil {
		return x.Observation
	}
	return nil
}

func (x *AgentState) GetReward() float32 {
	if x != nil {
		return x.Reward
	}
	return 0
}

func (x *AgentState) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

// 定义 Step 函数的请求体
type StepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action Action `protobuf:"varint,1,opt,name=action,proto3,enum=proto.Action" json:"action,omitempty"`
}

func (x *StepRequest) Reset() {
	*x = StepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_simulator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRequest) ProtoMessage() {}

func (x *StepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRequest.ProtoReflect.Descriptor instead.
func (*StepRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulator_proto_rawDescGZIP(), []int{2}
}

func (x *StepRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_WAIT
}

// 定义 Step 函数的响应体
type StepResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *AgentState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_simulator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulator_proto_rawDescGZIP(), []int{3}
}

func (x *StepResponse) GetState() *AgentState {
	if x != nil {
		return x.State
	}
	return nil
}

// 定义 Reset 函数的请求体 (通常为空)
type ResetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_simulator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulator_proto_rawDescGZIP(), []int{4}
}

// 定义 Reset 函数的响应体
type ResetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	State *AgentState `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_simulator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulator_proto_rawDescGZIP(), []int{5}
}

func (x *ResetResponse) GetState() *AgentState {
	if x != nil {
		return x.State
	}
	return nil
}

var File_proto_simulator_proto protoreflect.FileDescriptor

var file_proto_simulator_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf1,
	0x02, 0x0a, 0x10, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x69, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x5f, 0x62, 0x75, 0x73, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x69, 0x73,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x42, 0x75, 0x73, 0x79, 0x12, 0x27, 0x0a, 0x10, 0x68,
	0x61, 0x73, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x6f, 0x5f, 0x73, 0x65, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0d, 0x68, 0x61, 0x73, 0x44, 0x61, 0x74, 0x61, 0x54, 0x6f,
	0x53, 0x65, 0x6e, 0x64, 0x12, 0x3b, 0x0a, 0x1a, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x6e,
	0x64, 0x5f, 0x63, 0x61, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x17, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65,
	0x6e, 0x64, 0x43, 0x61, 0x75, 0x73, 0x65, 0x64, 0x43, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x2c, 0x0a, 0x12, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x62, 0x75, 0x73,
	0x79, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x42, 0x75, 0x73, 0x79, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x12,
	0x34, 0x0a, 0x16, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x63, 0x75, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x69,
	0x64, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x14, 0x63, 0x6f, 0x6e, 0x73, 0x65, 0x63, 0x75, 0x74, 0x69, 0x76, 0x65, 0x49, 0x64, 0x6c, 0x65,
	0x53, 0x74, 0x65, 0x70, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x5f,
	0x77, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x11, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x57, 0x61, 0x69, 0x74, 0x69, 0x6e,
	0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x1a, 0x73, 0x74, 0x65, 0x70, 0x73, 0x5f, 0x73,
	0x69, 0x6e, 0x63, 0x65, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x17, 0x73, 0x74, 0x65, 0x70, 0x73,
	0x53, 0x69, 0x6e, 0x63, 0x65, 0x4c, 0x61, 0x73, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x73, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x39, 0x0a, 0x0b, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b,
	0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x22, 0x34, 0x0a, 0x0b, 0x53, 0x74, 0x65, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x37, 0x0a,
	0x0c, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x2a, 0x2a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x57, 0x41, 0x49, 0x54, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x41,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x45, 0x4e, 0x44, 0x10, 0x01, 0x32, 0x74, 0x0a, 0x09,
	0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x31, 0x0a, 0x04, 0x53, 0x74, 0x65,
	0x70, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74,
	0x65, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x05,
	0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x41, 0x69, 0x72, 0x2d, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_simulator_proto_rawDescOnce sync.Once
	file_proto_simulator_proto_rawDescData = file_proto_simulator_proto_rawDesc
)

func file_proto_simulator_proto_rawDescGZIP() []byte {
	file_proto_simulator_proto_rawDescOnce.Do(func() {
		file_proto_simulator_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_simulator_proto_rawDescData)
	})
	return file_proto_simulator_proto_rawDescData
}

var file_proto_simulator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_simulator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_simulator_proto_goTypes = []interface{}{
	(Action)(0),              // 0: proto.Action
	(*AgentObservation)(nil), // 1: proto.AgentObservation
	(*AgentState)(nil),       // 2: proto.AgentState
	(*StepRequest)(nil),      // 3: proto.StepRequest
	(*StepResponse)(nil),     // 4: proto.StepResponse
	(*ResetRequest)(nil),     // 5: proto.ResetRequest
	(*ResetResponse)(nil),    // 6: proto.ResetResponse
}
var file_proto_simulator_proto_depIdxs = []int32{
	1, // 0: proto.AgentState.observation:type_name -> proto.AgentObservation
	0, // 1: proto.StepRequest.action:type_name -> proto.Action
	2, // 2: proto.StepResponse.state:type_name -> proto.AgentState
	2, // 3: proto.ResetResponse.state:type_name -> proto.AgentState
	3, // 4: proto.Simulator.Step:input_type -> proto.StepRequest
	5, // 5: proto.Simulator.Reset:input_type -> proto.ResetRequest
	4, // 6: proto.Simulator.Step:output_type -> proto.StepResponse
	6, // 7: proto.Simulator.Reset:output_type -> proto.ResetResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_simulator_proto_init() }
func file_proto_simulator_proto_init() {
	if File_proto_simulator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_simulator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentObservation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_simulator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_simulator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_simulator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StepResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_simulator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_simulator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_simulator_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_simulator_proto_goTypes,
		DependencyIndexes: file_proto_simulator_proto_depIdxs,
		EnumInfos:         file_proto_simulator_proto_enumTypes,
		MessageInfos:      file_proto_simulator_proto_msgTypes,
	}.Build()
	File_proto_simulator_proto = out.File
	file_proto_simulator_proto_rawDesc = nil
	file_proto_simulator_proto_goTypes = nil
	file_proto_simulator_proto_depIdxs = nil
}
